# Generated by Django 2.0.5 on 2018-10-31 08:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoaiSanPham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('ma_san_pham', models.AutoField(primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=100, unique=True)),
                ('hinh_san_pham', models.FileField(blank=True, upload_to='hinh_san_pham')),
                ('don_gia', models.FloatField()),
                ('giam_gia', models.FloatField()),
                ('size', models.IntegerField()),
                ('mo_ta_tom_tat', models.CharField(max_length=200)),
                ('mo_ta_chi_tiet', ckeditor_uploader.fields.RichTextUploadingField()),
                ('trang_thai', models.BooleanField(default=True)),
                ('loai_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoaiSanPham.LoaiSanPham')),
            ],
        ),
    ]
