# Generated by Django 2.0.5 on 2018-10-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoaiSanPham', '0001_initial'),
        ('SanPham', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonAn',
            new_name='SanPham',
        ),
    ]
