# Generated by Django 2.0.5 on 2018-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0002_auto_20181031_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_san_pham',
            field=models.ImageField(blank=True, upload_to='hinh_san_pham'),
        ),
    ]
