# Generated by Django 2.1.2 on 2018-11-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0003_auto_20181031_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanpham',
            old_name='don_gia',
            new_name='size_m',
        ),
        migrations.AddField(
            model_name='sanpham',
            name='size_s',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='ten_san_pham',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên sản phẩm'),
        ),
    ]
