# Generated by Django 2.1.2 on 2018-11-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0004_auto_20181101_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='size',
        ),
    ]
