# Generated by Django 2.1.2 on 2018-11-01 02:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0005_remove_sanpham_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='giam_gia',
            field=models.FloatField(verbose_name='Giảm giá'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_san_pham',
            field=models.ImageField(blank=True, upload_to='hinh_san_pham', verbose_name='Hình'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta_chi_tiet',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Chi tiết'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='mo_ta_tom_tat',
            field=models.CharField(max_length=200, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
    ]
