# Generated by Django 2.1.2 on 2018-11-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='tieu_de',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tiêu đề slider'),
        ),
    ]
