# Generated by Django 2.0.5 on 2018-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id_loai_san_pham', models.AutoField(primary_key=True, serialize=False)),
                ('ten_loai_san_pham', models.CharField(max_length=100, unique=True)),
                ('hinh_loai_san_pham', models.FileField(blank=True, upload_to='hinh_loai_san_pham')),
                ('ghi_chu', models.CharField(blank=True, max_length=500)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
    ]
